site_name: treefrog

repo_url: https://github.com/dawsonbooth/treefrog/
site_url: https://dawsonbooth.github.io/treefrog/

theme:
  name: material
  palette:
    primary: black
    accent: red

nav:
  - Overview: README.md
  - API Reference: api.md
