site_name: treefrog
nav:
  - Overview: README.md
  - Documentation: documentation.md
repo_url: https://github.com/dawsonbooth/treefrog/
site_url: https://dawsonbooth.github.io/treefrog/

markdown_extensions:
  - toc:
      permalink: 🔗

theme:
  name: readthedocs
